name: xiaomi_shop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0-83.0.dev <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.8.4
  flutter_swiper_view: ^1.1.8
  dio: ^5.2.0
  flutter_staggered_grid_view: ^0.6.2
  shared_preferences: ^2.1.2
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
  fonts:
    - family: iconFonts
      fonts:
        - asset: assets/fonts/iconfont.ttf

