name: xiaomi_shop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_screenutil: ^5.5.4
  flutter_swiper_view: ^1.1.8
  dio: ^5.6.0
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.0.15
  flutter_html: ^3.0.0-alpha.6
  pin_code_fields: ^8.0.1
  city_pickers: ^1.1.3
  crypto: ^3.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
  fonts:
    - family: iconFonts
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: userIcon
      fonts:
        - asset: assets/fonts/userIconfont.ttf

